apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ui.fullname" . }}-config
  labels:
    {{- include "ui.labels" . | nindent 4 }}
data:
  analytics: {{ .Values.config.analytics.token | quote }}
  appstore_asset_branch: {{ .Values.config.appstore_asset_branch }}
  brand_name: {{ .Values.config.brand_name }}
  hidden_support_sections: {{ .Values.config.hidden_support_sections | quote }}
  hidden_result_tabs: {{ .Values.config.hidden_result_tabs | quote }}
  search_enabled: {{ .Values.config.search.enabled | quote }}
  search_url: '{{ .Values.config.search.url }}'
  tranql_url: {{ .Values.config.tranql_url | quote }}
  workspaces_enabled: {{ .Values.config.workspaces.enabled | quote }}
