apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ui.fullname" . }}
  labels:
    {{- include "ui.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ui.selectorLabels" . | nindent  6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ui.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ui.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 100
            httpGet:
              path: /
              port: 80
          readinessProbe:
            initialDelaySeconds: 100
            httpGet:
              path: /
              port: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env: 
            - name: NODE_ENV
              value: production
            - name: REACT_APP_WORKSPACES_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ui.fullname" . }}-config
                  key: workspaces_enabled
            - name: REACT_APP_UI_BRAND_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ui.fullname" . }}-config
                  key: brand_name
            - name: REACT_APP_SEMANTIC_SEARCH_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ui.fullname" . }}-config
                  key: search_enabled
            - name: REACT_APP_HELX_SEARCH_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ui.fullname" . }}-config
                  key: search_url
            - name: REACT_APP_ANLAYTICS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ui.fullname" . }}-config
                  key: analytics
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
